# 应用服务 WEB 访问端口
server:
    port: 8080
    application:
        name: redis-demo
# 支持 swagger3
spring:
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    configuration:
        redis:
            database: 0
            host: localhost
            port: 6379

swagger:
    enable: true
    application-name: ${spring.application.name}
    application-version: 1.0
    application-description: 描述

    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
